/**
 * Industry Threshold Configuration
 * 
 * This file contains all industry-specific threshold mappings used for
 * calculating and evaluating stock scores. These thresholds define the
 * expected ranges and values for different industries.
 * 
 * To update these values, modify this file directly. The values are
 * automatically imported and used by the sheets services.
 */

/**
 * Industry to IRR (Internal Rate of Return) value mapping
 * Represents the expected IRR threshold for each industry
 */
export const INDUSTRY_IRR_MAP: Record<string, number> = {
  'Agricultural Inputs': 25,
  'Apparel Retail': 20,
  'Auto Parts': 25,
  'Airlines': 25,
  'Biotechnology': 30,
  'Beverages - Wineries & Distilleries': 0,
  'Building Products & Equipment': 20,
  'Capital Markets': 20,
  'Chemicals': 20,
  'Coking Coal': 25,
  'Communication Equipment': 20,
  'Computer Hardware': 20,
  'Copper': 25,
  'Conglomerates': 15,
  'Discount Stores': 20,
  'Drug Manufacturers - General': 20,
  'Drug Manufacturers - Specialty & Generic': 20,
  'Aluminum': 20,
  'Electrical Equipment & Parts': 20,
  'Electronic Components': 20,
  'Electronic Gaming & Multimedia': 25,
  'Engineering & Construction': 20,
  'Farm & Heavy Construction Machinery': 20,
  'Farm Products': 20,
  'Footwear & Accessories': 20,
  'Gambling': 25,
  'Healthcare Plans': 20,
  'Industrial Distribution': 20,
  'Information Technology Services': 20,
  'Internet Content & Information': 35,
  'Internet Retail': 25,
  'Leisure': 20,
  'Luxury Goods': 20,
  'Marine Shipping': 25,
  'Medical Care Facilities': 20,
  'Medical Instruments & Supplies': 20,
  'Oil & Gas Exploration & Production & Integrated & Equipment & Services & Drilling': 26,
  'Oil & Gas Integrated': 22,
  'Oil & Gas Midstream': 15,
  'Oil & Gas Refining & Marketing': 20,
  'Other Industrial Metals & Mining': 25,
  'Other Precious Metals & Mining': 25,
  'Packaged Foods': 15,
  'Packaging & Containers': 20,
  'Pollution & Treatment Controls': 20,
  'Railroads': 16,
  'Real Estate Services': 15,
  'Recreational Vehicles': 20,
  'REIT - Industrial': 15,
  'REIT - Specialty': 15,
  'Residential Construction': 20,
  'Scientific & Technical Instruments': 20,
  'Security & Protection Services': 20,
  'Semiconductor Equipment & Materials': 25,
  'Semiconductors': 25,
  'Software': 35,
  'Solar': 25,
  'Specialty Business Services': 20,
  'Specialty Chemicals': 20,
  'Specialty Industrial Machinery': 20,
  'Steel': 25,
  'Telecom Services': 20,
  'Thermal Coal': 25,
  'Utilities - Regulated Electric': 15,
  'Utilities - Regulated Water': 15,
  'Utilities - Renewable': 15,
  'Waste Management': 15,
};

/**
 * Industry to Leverage F2 mapping
 * Defines green (max) and red (min) thresholds for leverage ratios
 * Note: greenMax is the maximum value for green status, redMin is the minimum value for red status
 */
export const INDUSTRY_LEVERAGE_F2_MAP: Record<string, { greenMax: number; redMin: number }> = {
  'Agricultural Inputs': { greenMax: 2.0, redMin: 3.0 },
  'Apparel Retail': { greenMax: 2.0, redMin: 3.0 },
  'Auto Parts': { greenMax: 2.0, redMin: 3.0 },
  'Airlines': { greenMax: 2.5, redMin: 4.0 },
  'Biotechnology': { greenMax: 1.0, redMin: 2.0 },
  'Beverages - Wineries & Distilleries': { greenMax: 0, redMin: 0 },
  'Building Products & Equipment': { greenMax: 2.0, redMin: 3.0 },
  'Chemicals': { greenMax: 2.0, redMin: 3.0 },
  'Coking Coal': { greenMax: 1.5, redMin: 2.5 },
  'Communication Equipment': { greenMax: 1.5, redMin: 2.5 },
  'Computer Hardware': { greenMax: 1.5, redMin: 2.5 },
  'Conglomerates': { greenMax: 2.5, redMin: 3.5 },
  'Copper': { greenMax: 1.5, redMin: 2.5 },
  'Discount Stores': { greenMax: 2.0, redMin: 3.0 },
  'Drug Manufacturers - General': { greenMax: 2.0, redMin: 3.0 },
  'Drug Manufacturers - Specialty & Generic': { greenMax: 2.5, redMin: 3.5 },
  'Electrical Equipment & Parts': { greenMax: 2.0, redMin: 3.0 },
  'Electronic Components': { greenMax: 1.5, redMin: 2.5 },
  'Aluminum': { greenMax: 1.5, redMin: 2.5 },
  'Electronic Gaming & Multimedia': { greenMax: 2.0, redMin: 3.5 },
  'Engineering & Construction': { greenMax: 1.5, redMin: 2.5 },
  'Farm & Heavy Construction Machinery': { greenMax: 2.0, redMin: 3.0 },
  'Farm Products': { greenMax: 2.0, redMin: 3.0 },
  'Footwear & Accessories': { greenMax: 1.5, redMin: 3.0 },
  'Gambling': { greenMax: 3.0, redMin: 4.5 },
  'Industrial Distribution': { greenMax: 2.0, redMin: 3.0 },
  'Information Technology Services': { greenMax: 1.5, redMin: 2.5 },
  'Internet Content & Information': { greenMax: 1.5, redMin: 2.5 },
  'Internet Retail': { greenMax: 2.0, redMin: 3.0 },
  'Leisure': { greenMax: 2.0, redMin: 3.0 },
  'Luxury Goods': { greenMax: 2.0, redMin: 3.0 },
  'Marine Shipping': { greenMax: 2.0, redMin: 3.0 },
  'Medical Care Facilities': { greenMax: 3.0, redMin: 4.5 },
  'Medical Instruments & Supplies': { greenMax: 1.5, redMin: 2.5 },
  'Oil & Gas Exploration & Production & Integrated & Equipment & Services & Drilling': { greenMax: 1.5, redMin: 3.0 },
  'Oil & Gas Integrated': { greenMax: 2.0, redMin: 3.0 },
  'Oil & Gas Midstream (Pipelines)': { greenMax: 3.5, redMin: 4.5 },
  'Oil & Gas Refining & Marketing': { greenMax: 2.0, redMin: 3.0 },
  'Other Industrial Metals & Mining': { greenMax: 1.5, redMin: 2.5 },
  'Other Precious Metals & Mining': { greenMax: 1.5, redMin: 2.5 },
  'Packaged Foods': { greenMax: 2.5, redMin: 3.5 },
  'Packaging & Containers': { greenMax: 2.5, redMin: 3.5 },
  'Pollution & Treatment Controls': { greenMax: 2.5, redMin: 3.5 },
  'Railroads': { greenMax: 3.0, redMin: 3.5 },
  'Real Estate Services': { greenMax: 1.5, redMin: 2.5 },
  'Recreational Vehicles': { greenMax: 2.0, redMin: 3.0 },
  'REIT - Industrial': { greenMax: 5.0, redMin: 6.5 },
  'REIT - Specialty': { greenMax: 5.5, redMin: 7.0 },
  'Residential Construction': { greenMax: 2.0, redMin: 3.0 },
  'Scientific & Technical Instruments': { greenMax: 1.5, redMin: 2.5 },
  'Security & Protection Services': { greenMax: 2.0, redMin: 3.0 },
  'Semiconductor Equipment & Materials': { greenMax: 1.5, redMin: 2.5 },
  'Semiconductors': { greenMax: 1.5, redMin: 2.5 },
  'Software': { greenMax: 1.5, redMin: 2.5 },
  'Solar': { greenMax: 2.0, redMin: 3.0 },
  'Specialty Business Services': { greenMax: 2.0, redMin: 3.0 },
  'Specialty Chemicals': { greenMax: 2.0, redMin: 3.0 },
  'Specialty Industrial Machinery': { greenMax: 2.0, redMin: 3.0 },
  'Steel': { greenMax: 1.5, redMin: 2.5 },
  'Telecom Services': { greenMax: 3.0, redMin: 4.0 },
  'Thermal Coal': { greenMax: 1.5, redMin: 2.5 },
  'Utilities - Regulated Electric': { greenMax: 4.5, redMin: 6.0 },
  'Utilities - Regulated Water': { greenMax: 4.5, redMin: 6.0 },
  'Utilities - Renewable': { greenMax: 4.0, redMin: 5.0 },
  'Waste Management': { greenMax: 3.0, redMin: 4.0 },
  'Capital Markets': { greenMax: 2.0, redMin: 3.0 },
  'Healthcare Plans': { greenMax: 2.0, redMin: 3.0 },
  'Oil & Gas Midstream': { greenMax: 3.5, redMin: 4.5 },
};

/**
 * Industry to RO40 mapping (Return on Assets)
 * Defines the expected min and max range for RO40 values by industry
 */
export const INDUSTRY_RO40_MAP: Record<string, { min: number; max: number }> = {
  'Oil & Gas Exploration & Production & Integrated & Equipment & Services & Drilling': { min: 0.15, max: 0.25 },
  'Discount Stores': { min: 0.25, max: 0.40 },
  'Drug Manufacturers - General': { min: 0.30, max: 0.45 },
  'Semiconductor Equipment & Materials': { min: 0.30, max: 0.45 },
  'Auto Parts': { min: 0.25, max: 0.40 },
  'Communication Equipment': { min: 0.25, max: 0.40 },
  'Information Technology Services': { min: 0.30, max: 0.45 },
  'Specialty Chemicals': { min: 0.25, max: 0.40 },
  'Building Products & Equipment': { min: 0.25, max: 0.40 },
  'Capital Markets': { min: 0.25, max: 0.40 },
  'Electrical Equipment & Parts': { min: 0.25, max: 0.40 },
  'Footwear & Accessories': { min: 0.25, max: 0.40 },
  'Gambling': { min: 0.25, max: 0.40 },
  'Marine Shipping': { min: 0.15, max: 0.25 },
  'Medical Instruments & Supplies': { min: 0.30, max: 0.45 },
  'Oil & Gas Integrated': { min: 0.15, max: 0.25 },
  'Semiconductors': { min: 0.30, max: 0.45 },
  'Solar': { min: 0.25, max: 0.40 },
  'Specialty Industrial Machinery': { min: 0.25, max: 0.40 },
  'Utilities - Renewable': { min: 0.15, max: 0.25 },
  'Agricultural Inputs': { min: 0.15, max: 0.25 },
  'Apparel Retail': { min: 0.25, max: 0.40 },
  'Biotechnology': { min: 0.20, max: 0.30 },
  'Beverages - Wineries & Distilleries': { min: 0, max: 0 },
  'Chemicals': { min: 0.25, max: 0.40 },
  'Coking Coal': { min: 0.15, max: 0.25 },
  'Conglomerates': { min: 0.25, max: 0.40 },
  'Electronic Gaming & Multimedia': { min: 0.40, max: 0.55 },
  'Farm Products': { min: 0.15, max: 0.25 },
  'Healthcare Plans': { min: 0.25, max: 0.40 },
  'Industrial Distribution': { min: 0.20, max: 0.30 },
  'Internet Retail': { min: 0.20, max: 0.30 },
  'Oil & Gas Refining & Marketing': { min: 0.15, max: 0.25 },
  'Other Industrial Metals & Mining': { min: 0.15, max: 0.25 },
  'Pollution & Treatment Controls': { min: 0.25, max: 0.40 },
  'Railroads': { min: 0.25, max: 0.40 },
  'REIT - Specialty': { min: 0.15, max: 0.25 },
  'Residential Construction': { min: 0.20, max: 0.30 },
  'Security & Protection Services': { min: 0.25, max: 0.40 },
  'Software': { min: 0.40, max: 0.55 },
  'Specialty Business Services': { min: 0.25, max: 0.40 },
  'Steel': { min: 0.15, max: 0.25 },
  'Telecom Services': { min: 0.15, max: 0.25 },
  'Thermal Coal': { min: 0.15, max: 0.25 },
  'Utilities - Regulated Electric': { min: 0.15, max: 0.25 },
  'Utilities - Regulated Water': { min: 0.15, max: 0.25 },
  'Waste Management': { min: 0.20, max: 0.30 },
  'Computer Hardware': { min: 0.25, max: 0.40 },
  'Copper': { min: 0.15, max: 0.25 },
  'Drug Manufacturers - Specialty & Generic': { min: 0.25, max: 0.40 },
  'Electronic Components': { min: 0.25, max: 0.40 },
  'Engineering & Construction': { min: 0.20, max: 0.30 },
  'Farm & Heavy Construction Machinery': { min: 0.20, max: 0.30 },
  'Internet Content & Information': { min: 0.40, max: 0.55 },
  'Leisure': { min: 0.25, max: 0.40 },
  'Luxury Goods': { min: 0.30, max: 0.45 },
  'Medical Care Facilities': { min: 0.20, max: 0.30 },
  'Oil & Gas Midstream (Pipelines)': { min: 0.15, max: 0.25 },
  'Other Precious Metals & Mining': { min: 0.15, max: 0.25 },
  'Packaged Foods': { min: 0.20, max: 0.30 },
  'Packaging & Containers': { min: 0.20, max: 0.30 },
  'Real Estate Services': { min: 0.20, max: 0.30 },
  'Recreational Vehicles': { min: 0.20, max: 0.30 },
  'REIT - Industrial': { min: 0.15, max: 0.25 },
  'Scientific & Technical Instruments': { min: 0.30, max: 0.45 },
  'Aluminum': { min: 0.15, max: 0.25 },
  'Airlines': { min: 0.15, max: 0.25 },
  'Oil & Gas Midstream': { min: 0.15, max: 0.25 },
};

/**
 * Industry to Cash/SDebt mapping
 * Defines the expected min and max range for Cash/SDebt ratios by industry
 */
export const INDUSTRY_CASH_SDEBT_MAP: Record<string, { min: number; max: number }> = {
  'Oil & Gas Exploration & Production & Integrated & Equipment & Services & Drilling': { min: 0.7, max: 1.2 },
  'Discount Stores': { min: 0.6, max: 1.0 },
  'Airlines': { min: 0.8, max: 1.1 },
  'Drug Manufacturers - General': { min: 1.0, max: 1.5 },
  'Semiconductor Equipment & Materials': { min: 1.0, max: 1.5 },
  'Auto Parts': { min: 0.8, max: 1.1 },
  'Communication Equipment': { min: 0.8, max: 1.2 },
  'Information Technology Services': { min: 1.0, max: 1.5 },
  'Specialty Chemicals': { min: 0.7, max: 1.0 },
  'Building Products & Equipment': { min: 0.8, max: 1.2 },
  'Electrical Equipment & Parts': { min: 0.8, max: 1.1 },
  'Footwear & Accessories': { min: 0.6, max: 1.0 },
  'Gambling': { min: 0.8, max: 1.1 },
  'Marine Shipping': { min: 0.9, max: 1.3 },
  'Medical Instruments & Supplies': { min: 0.8, max: 1.2 },
  'Oil & Gas Integrated': { min: 0.7, max: 1.0 },
  'Semiconductors': { min: 1.2, max: 1.8 },
  'Solar': { min: 0.8, max: 1.2 },
  'Specialty Industrial Machinery': { min: 0.8, max: 1.1 },
  'Utilities - Renewable': { min: 0.7, max: 1.0 },
  'Agricultural Inputs': { min: 0.8, max: 1.1 },
  'Apparel Retail': { min: 0.6, max: 1.0 },
  'Biotechnology': { min: 1.2, max: 2.0 },
  'Beverages - Wineries & Distilleries': { min: 0, max: 0 },
  'Chemicals': { min: 0.7, max: 1.0 },
  'Coking Coal': { min: 0.8, max: 1.2 },
  'Conglomerates': { min: 0.8, max: 1.2 },
  'Electronic Gaming & Multimedia': { min: 1.0, max: 1.5 },
  'Farm Products': { min: 0.8, max: 1.1 },
  'Industrial Distribution': { min: 0.8, max: 1.1 },
  'Internet Retail': { min: 0.8, max: 1.2 },
  'Oil & Gas Refining & Marketing': { min: 0.8, max: 1.2 },
  'Other Industrial Metals & Mining': { min: 0.8, max: 1.2 },
  'Pollution & Treatment Controls': { min: 0.8, max: 1.1 },
  'Railroads': { min: 0.8, max: 1.1 },
  'REIT - Specialty': { min: 0.5, max: 0.8 },
  'Residential Construction': { min: 0.8, max: 1.2 },
  'Security & Protection Services': { min: 0.8, max: 1.2 },
  'Software': { min: 1.3, max: 2.0 },
  'Specialty Business Services': { min: 0.8, max: 1.2 },
  'Steel': { min: 0.8, max: 1.1 },
  'Telecom Services': { min: 0.6, max: 0.9 },
  'Thermal Coal': { min: 0.8, max: 1.2 },
  'Utilities - Regulated Electric': { min: 0.5, max: 0.8 },
  'Utilities - Regulated Water': { min: 0.5, max: 0.8 },
  'Waste Management': { min: 0.6, max: 0.9 },
  'Computer Hardware': { min: 0.9, max: 1.3 },
  'Copper': { min: 0.8, max: 1.2 },
  'Drug Manufacturers - Specialty & Generic': { min: 0.9, max: 1.3 },
  'Electronic Components': { min: 0.8, max: 1.2 },
  'Engineering & Construction': { min: 0.8, max: 1.2 },
  'Farm & Heavy Construction Machinery': { min: 0.8, max: 1.1 },
  'Internet Content & Information': { min: 1.0, max: 1.5 },
  'Leisure': { min: 0.8, max: 1.2 },
  'Luxury Goods': { min: 0.9, max: 1.3 },
  'Medical Care Facilities': { min: 0.7, max: 1.0 },
  'Oil & Gas Midstream (Pipelines)': { min: 0.6, max: 0.9 },
  'Other Precious Metals & Mining': { min: 0.8, max: 1.2 },
  'Packaged Foods': { min: 0.6, max: 0.9 },
  'Packaging & Containers': { min: 0.6, max: 0.9 },
  'Real Estate Services': { min: 0.8, max: 1.2 },
  'Recreational Vehicles': { min: 0.8, max: 1.2 },
  'REIT - Industrial': { min: 0.5, max: 0.8 },
  'Scientific & Technical Instruments': { min: 0.8, max: 1.2 },
  'Aluminum': { min: 0.8, max: 1.2 },
  'Capital Markets': { min: 0.8, max: 1.2 },
  'Healthcare Plans': { min: 0.8, max: 1.2 },
  'Oil & Gas Midstream': { min: 0.6, max: 0.9 },
};

/**
 * Industry to Current Ratio mapping
 * Defines the expected min and max range for Current Ratio values by industry
 */
export const INDUSTRY_CURRENT_RATIO_MAP: Record<string, { min: number; max: number }> = {
  'Agricultural Inputs': { min: 1.1, max: 2.0 },
  'Airlines': { min: 0.5, max: 1.2 },
  'Aluminum': { min: 1.1, max: 2.2 },
  'Apparel Retail': { min: 0.8, max: 1.5 },
  'Auto Parts': { min: 1.1, max: 1.8 },
  'Biotechnology': { min: 1.5, max: 4.0 },
  'Beverages - Wineries & Distilleries': { min: 0, max: 0 },
  'Building Products & Equipment': { min: 1.2, max: 2.0 },
  'Capital Markets': { min: 1.0, max: 1.4 },
  'Chemicals': { min: 1.2, max: 2.0 },
  'Coking Coal': { min: 1.1, max: 2.0 },
  'Communication Equipment': { min: 1.2, max: 2.0 },
  'Computer Hardware': { min: 1.2, max: 2.0 },
  'Conglomerates': { min: 1.2, max: 2.0 },
  'Copper': { min: 1.2, max: 2.5 },
  'Discount Stores': { min: 0.8, max: 1.4 },
  'Drug Manufacturers - General': { min: 1.3, max: 2.5 },
  'Drug Manufacturers - Specialty & Generic': { min: 1.2, max: 2.2 },
  'Electrical Equipment & Parts': { min: 1.2, max: 2.0 },
  'Electronic Components': { min: 1.2, max: 2.0 },
  'Electronic Gaming & Multimedia': { min: 1.0, max: 2.0 },
  'Engineering & Construction': { min: 1.1, max: 1.8 },
  'Farm & Heavy Construction Machinery': { min: 1.2, max: 2.0 },
  'Farm Products': { min: 1.1, max: 2.0 },
  'Footwear & Accessories': { min: 1.1, max: 2.0 },
  'Gambling': { min: 0.9, max: 1.5 },
  'Healthcare Plans': { min: 1.0, max: 1.6 },
  'Industrial Distribution': { min: 1.0, max: 1.8 },
  'Information Technology Services': { min: 1.0, max: 1.8 },
  'Internet Content & Information': { min: 1.0, max: 2.0 },
  'Internet Retail': { min: 0.8, max: 1.5 },
  'Leisure': { min: 1.0, max: 1.6 },
  'Luxury Goods': { min: 1.2, max: 2.2 },
  'Marine Shipping': { min: 1.0, max: 2.0 },
  'Medical Care Facilities': { min: 1.0, max: 1.7 },
  'Medical Instruments & Supplies': { min: 1.5, max: 3.0 },
  'Oil & Gas Exploration & Production & Integrated & Equipment & Services & Drilling': { min: 1.0, max: 1.8 },
  'Oil & Gas Integrated': { min: 0.9, max: 1.5 },
  'Oil & Gas Midstream (Pipelines)': { min: 0.9, max: 1.4 },
  'Oil & Gas Refining & Marketing': { min: 0.9, max: 1.5 },
  'Other Industrial Metals & Mining': { min: 1.2, max: 2.5 },
  'Other Precious Metals & Mining': { min: 1.5, max: 3.0 },
  'Packaged Foods': { min: 1.0, max: 1.8 },
  'Packaging & Containers': { min: 1.1, max: 1.9 },
  'Pollution & Treatment Controls': { min: 1.2, max: 2.0 },
  'Railroads': { min: 0.9, max: 1.5 },
  'Real Estate Services': { min: 1.0, max: 1.6 },
  'Recreational Vehicles': { min: 1.2, max: 2.2 },
  'REIT - Industrial': { min: 0.7, max: 1.3 },
  'REIT - Specialty': { min: 0.7, max: 1.3 },
  'Residential Construction': { min: 2.0, max: 4.0 },
  'Scientific & Technical Instruments': { min: 1.3, max: 2.2 },
  'Security & Protection Services': { min: 1.0, max: 1.6 },
  'Semiconductor Equipment & Materials': { min: 1.2, max: 2.5 },
  'Semiconductors': { min: 1.2, max: 2.0 },
  'Software': { min: 0.6, max: 1.5 },
  'Solar': { min: 1.1, max: 2.0 },
  'Specialty Business Services': { min: 1.0, max: 1.6 },
  'Specialty Chemicals': { min: 1.2, max: 2.0 },
  'Specialty Industrial Machinery': { min: 1.2, max: 2.0 },
  'Steel': { min: 1.1, max: 2.2 },
  'Telecom Services': { min: 0.8, max: 1.3 },
  'Thermal Coal': { min: 1.1, max: 2.0 },
  'Utilities - Regulated Electric': { min: 0.8, max: 1.2 },
  'Utilities - Regulated Water': { min: 0.8, max: 1.3 },
  'Utilities - Renewable': { min: 1.0, max: 1.8 },
  'Waste Management': { min: 0.9, max: 1.4 },
  'Oil & Gas Midstream': { min: 0.9, max: 1.4 },
};

