/* eslint-disable -- generated by scripts/sync-eodhd-exchanges.mjs */
/* Do not edit by hand. Regenerate: npm run eodhd:sync-exchanges */
/** Uppercase lookup → canonical `Code` string from EODHD exchanges-list */
export const EODHD_EXCHANGE_CODE_CANONICAL: Readonly<Record<string, string>> = {
  "AS": "AS",
  "AU": "AU",
  "CC": "CC",
  "CN": "CN",
  "CO": "CO",
  "FOREX": "FOREX",
  "HA": "HA",
  "HE": "HE",
  "HO": "HO",
  "IC": "IC",
  "IR": "IR",
  "JK": "JK",
  "KO": "KO",
  "LSE": "LSE",
  "MC": "MC",
  "MI": "MI",
  "MU": "MU",
  "NEO": "NEO",
  "OL": "OL",
  "OTCMKTS": "OTCMKTS",
  "PA": "PA",
  "SA": "SA",
  "ST": "ST",
  "SW": "SW",
  "TO": "TO",
  "TWO": "TWO",
  "US": "US",
  "VI": "VI",
  "WAR": "WAR",
  "XETRA": "XETRA",
};

export function canonicalEodhdExchangeCode(upper: string): string | null {
  const k = upper.trim().toUpperCase();
  return EODHD_EXCHANGE_CODE_CANONICAL[k] ?? null;
}
